version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: yumyumcoach-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: yumyumcoach
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data:
